[loggers]
keys=root,fileLogger

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=WARN
handlers=consoleHandler
qualname=MainLogger
propagate=0

[logger_file]
level=INFO
handlers=fileHandler
qualname=fileLogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
formatter=simpleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
formatter=simpleFormatter
args=('%(logname)s', 'a')

[formatter_simpleFormatter]
format=%(asctime)s [%(levelname)s] %(message)s
